# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sisbase', models.IntegerField(verbose_name='ID Sisbase')),
                ('name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('invoice', models.CharField(max_length=40, verbose_name='Numero Factura')),
                ('date', models.DateField(verbose_name='Fecha Maxima')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Factura')),
                ('ip_address', models.GenericIPAddressField(protocol='ipv4', verbose_name='Ip')),
            ],
        ),
    ]
