# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='seeme',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Visto'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='id_sisbase',
            field=models.IntegerField(unique=True, verbose_name='ID Sisbase'),
        ),
    ]
