# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20160628_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='seeme',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Visto'),
        ),
    ]
