# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overdue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sisbase', models.IntegerField(unique=True, verbose_name='ID Sisbase')),
                ('name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('pending', models.PositiveSmallIntegerField(verbose_name='Facturas Pendientes')),
                ('ip_address', models.GenericIPAddressField(protocol='ipv4', verbose_name='Ip')),
                ('seeme', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Visto')),
            ],
        ),
    ]
