# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='overdue',
            name='removed',
            field=models.BooleanField(default=True, verbose_name='Regla Removida'),
        ),
    ]
